name = "Hexwoven"
author = "Teal Wolf 25"
version = "5.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bce69acaba9e4c76b976174b965a35c4b101491e1118cb4c84212812997e7c21"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
