name = "Hexwoven"
author = "Teal Wolf 25"
version = "5.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6ded56e5884e9fc39e5a092e0d1c4c5702c36ff341c845834991e088de5bb6d"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
