name = "Hexwoven"
author = "Teal Wolf 25"
version = "5.1.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "46fe00d319b1414ad40256333be8478c60e683cc2e116e08368483d19cc0eefb"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
